GET  http://localhost:8080/bye
###

POST http://localhost:8080/hi
###

GET http://www.moomoo.dev:8080/bye
###

POST http://www.moomoo.dev:8080/hi
###

POST http://www.moomoo.dev:3000/hi

###
GET http://localhost:8080/study2/example1?a=a1&b=b1

###
POST  http://localhost:8080/study2/example2
Content-Type: application/json

{"a": "a2", "b": "b2"}

###
POST http://localhost:8080/study2/example3/a3
Content-Type: application/x-www-form-urlencoded

b=b3&c=c3

###
POST http://localhost:8080/study2/example4
Header-A: a4
Header-B: b4
Header-C: c4
###